# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: littlelv2001的技术博客
email: 18965050@qq.com
description: > # this means to ignore newlines until "baseurl:"
  很高兴终于在github pages上开设博客了.目前对于jekyll还不是很熟悉,后面会尽快更新博客页面, 形成自己风格,
  并将之前写的文章逐步移植过来.
  希望大家多多支持!!!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://18965050.github.io/" # the base hostname & protocol for your site
twitter_username: 18965050
github_username:  18965050

# Build settings
markdown: kramdown
